### ISSUE TITLE
"No search module is selected" after "lazyLoad" and "initialize" with "-lm" and "-dict" for live_zh demo

### ISSUE THREAD

**Issue by xinxu75** [syl22-00/pocketsphinx.js#111]
Hi there,

I try to modify the live_zh.html demo by lazyloading the official CMUSphinx acoustic, lm and dictionary for Chinese, within spawnWorker(). After that, within initRecognizer(), "initialize" with "-lm", "-dict", "-hmm", "-samprate" is called, as discussed in "README" and previous issues. However, I have the following error when running the modified demo --
ERROR: "pocketsphinx.c", line 816: No search module is selected, did you forget to specify a language model or grammar?

I list the codes of lazyload and initialize below - the folder structure follows the README instructions:
js folder, which has all the relevant .js files
zh_broadcastnews_ptm256_8000 folder, which has all the acoustic files
zh_broadcastnews_utf8.dic file
zh_broadcastnews_64000_utf8.DMP file

Just wondering if and where I did anything incorrect? If you could kindly help with issue, that would be much appreciated.

Thanks a lot

------------------------------------------------------------------
Within spawnWorker(): 

postRecognizerJob({command: 'lazyLoad',
              data: {folders: [["/", "zh_broadcastnews_ptm256_8000"]], 
            	  files: [["/zh_broadcastnews_ptm256_8000", "means", "../zh_broadcastnews_ptm256_8000/means"],
        			  ["/zh_broadcastnews_ptm256_8000", "variances", "../zh_broadcastnews_ptm256_8000/variances"],
        			  ["/zh_broadcastnews_ptm256_8000", "transition_matrices", "../zh_broadcastnews_ptm256_8000/transition_matrices"],
        			  ["/zh_broadcastnews_ptm256_8000", "sendump", "../zh_broadcastnews_ptm256_8000/sendump"],		       
        			  ["/zh_broadcastnews_ptm256_8000", "mdef", "../zh_broadcastnews_ptm256_8000/mdef"],		       
        			  ["/zh_broadcastnews_ptm256_8000", "feat.params", "../zh_broadcastnews_ptm256_8000/feat.params"],		       
        			  ["/zh_broadcastnews_ptm256_8000", "mixture_weights", "../zh_broadcastnews_ptm256_8000/mixture_weights"],	       
        			  ["/zh_broadcastnews_ptm256_8000", "noisedict", "../zh_broadcastnews_ptm256_8000/noisedict"]]}
          }, function(){console.log("lazyLoad first batch done")});

          
postRecognizerJob({command: 'lazyLoad',
              data: {folders: [], files: [["/", "zh_broadcastnews_utf8.dic", "../zh_broadcastnews_utf8.dic"],
                                          ["/", zh_broadcastnews_64000_utf8.DMP", "../zh_broadcastnews_64000_utf8.DMP"]]}
             }, initRecognizer());

-------------------------------------------------------

var initRecognizer = function() {
        // You can pass parameters to the recognizer, such as : {command: 'initialize', data: [["-hmm", "my_model"], ["-fwdflat", "no"]]}
        // Pay attention here to state the sample rate as the default value is 16kHz and this Chinese acoustic model uses 8kHz
        postRecognizerJob({command: 'initialize', data:[
        	["-lm", "zh_broadcastnews_64000_utf8.DMP"],
        	["-dict", "zh_broadcastnews_utf8.dic"], 
        	["-samprate", "8000"], 
        	["-hmm", "zh_broadcastnews_ptm256_8000"],
        	["-fwdflat", "no"]
        	]},                          
        	function() {                                      
        		if (recorder) recorder.consumers = [recognizer];
        		recognizerReady();               
        	}	
        );
};

**Comment by syl22-00** [comment]
It seems like the language model or dictionary was not loaded successfully as it says no search module was selected. Please give the whole output from the console, it would be easier to see what is missing.

**Comment by xinxu75** [comment]
Thanks Sylvain for the response, 

Please see the full console output below, where I commented out my own debug console output "lazyLoad first batch done". Also in my code I lazyLoad twice as the following files are in different folders: the first to load acoustic model, and the second to load dictionary and language model. I guess this shouldn't matter?

Thanks a lot
-----------------------------------------------------------------
INFO: cmd_ln.c(696): Parsing command line:
pocketsphinx_zh.js:1 \
pocketsphinx_zh.js:1 	-bestpath no \
pocketsphinx_zh.js:1 	-fwdflat no \
pocketsphinx_zh.js:1 	-hmm tdt_sc_8k \
pocketsphinx_zh.js:1 	-remove_noise no \
pocketsphinx_zh.js:1 	-samprate 8000 (null) (null) (null) (null) 
pocketsphinx_zh.js:1 
pocketsphinx_zh.js:1 Current configuration:
pocketsphinx_zh.js:1 [NAME]		[DEFLT]		[VALUE]
pocketsphinx_zh.js:1 -adcdev				
pocketsphinx_zh.js:1 -agc		none		none
pocketsphinx_zh.js:1 -agcthresh	2.0		2.000000e+00
pocketsphinx_zh.js:1 -alpha		0.97		9.700000e-01
pocketsphinx_zh.js:1 -argfile			
pocketsphinx_zh.js:1 -ascale		20.0		2.000000e+01
pocketsphinx_zh.js:1 -aw		1		1
pocketsphinx_zh.js:1 -backtrace	no		no
pocketsphinx_zh.js:1 -beam		1e-48		1.000000e-48
pocketsphinx_zh.js:1 -bestpath	yes		no
pocketsphinx_zh.js:1 -bestpathlw	9.5		9.500000e+00
pocketsphinx_zh.js:1 -bghist		no		no
pocketsphinx_zh.js:1 -ceplen		13		13
pocketsphinx_zh.js:1 -cmn		current		current
pocketsphinx_zh.js:1 -cmninit	8.0		8.0
pocketsphinx_zh.js:1 -compallsen	no		no
pocketsphinx_zh.js:1 -debug				0
pocketsphinx_zh.js:1 -dict				
pocketsphinx_zh.js:1 -dictcase	no		no
pocketsphinx_zh.js:1 -dither		no		no
pocketsphinx_zh.js:1 -doublebw	no		no
pocketsphinx_zh.js:1 -ds		1		1
pocketsphinx_zh.js:1 -fdict				
pocketsphinx_zh.js:1 -feat		1s_c_d_dd	1s_c_d_dd
pocketsphinx_zh.js:1 -featparams			
pocketsphinx_zh.js:1 -fillprob	1e-8		1.000000e-08
pocketsphinx_zh.js:1 -frate		100		100
pocketsphinx_zh.js:1 -fsg				
pocketsphinx_zh.js:1 -fsgusealtpron	yes		yes
pocketsphinx_zh.js:1 -fsgusefiller	yes		yes
pocketsphinx_zh.js:1 -fwdflat	yes		no
pocketsphinx_zh.js:1 -fwdflatbeam	1e-64		1.000000e-64
pocketsphinx_zh.js:1 -fwdflatefwid	4		4
pocketsphinx_zh.js:1 -fwdflatlw	8.5		8.500000e+00
pocketsphinx_zh.js:1 -fwdflatsfwin	25		25
pocketsphinx_zh.js:1 -fwdflatwbeam	7e-29		7.000000e-29
pocketsphinx_zh.js:1 -fwdtree	yes		yes
pocketsphinx_zh.js:1 -hmm				tdt_sc_8k
pocketsphinx_zh.js:1 -infile				
pocketsphinx_zh.js:1 -input_endian	little		little
pocketsphinx_zh.js:1 -jsgf				
pocketsphinx_zh.js:1 -kdmaxbbi	-1		-1
pocketsphinx_zh.js:1 -kdmaxdepth	0		0
pocketsphinx_zh.js:1 -kdtree				
pocketsphinx_zh.js:1 -keyphrase			
pocketsphinx_zh.js:1 -kws				
pocketsphinx_zh.js:1 -kws_plp	1e-1		1.000000e-01
pocketsphinx_zh.js:1 -kws_threshold	1		1.000000e+00
pocketsphinx_zh.js:1 -latsize	5000		5000
pocketsphinx_zh.js:1 -lda				
pocketsphinx_zh.js:1 -ldadim		0		0
pocketsphinx_zh.js:1 -lextreedump	0		0
pocketsphinx_zh.js:1 -lifter		0		0
pocketsphinx_zh.js:1 -lm				
pocketsphinx_zh.js:1 -lmctl				
pocketsphinx_zh.js:1 -lmname		default		default
pocketsphinx_zh.js:1 -logbase	1.0001		1.000100e+00
pocketsphinx_zh.js:1 -logfn				
pocketsphinx_zh.js:1 -logspec	no		no
pocketsphinx_zh.js:1 -lowerf		133.33334	1.333333e+02
pocketsphinx_zh.js:1 -lpbeam		1e-40		1.000000e-40
pocketsphinx_zh.js:1 -lponlybeam	7e-29		7.000000e-29
pocketsphinx_zh.js:1 -lw		6.5		6.500000e+00
pocketsphinx_zh.js:1 -maxhmmpf	10000		10000
pocketsphinx_zh.js:1 -maxnewoov	20		20
pocketsphinx_zh.js:1 -maxwpf		-1		-1
pocketsphinx_zh.js:1 -mdef				
pocketsphinx_zh.js:1 -mean				
pocketsphinx_zh.js:1 -mfclogdir			
pocketsphinx_zh.js:1 -min_endfr	0		0
pocketsphinx_zh.js:1 -mixw				
pocketsphinx_zh.js:1 -mixwfloor	0.0000001	1.000000e-07
pocketsphinx_zh.js:1 -mllr				
pocketsphinx_zh.js:1 -mmap		yes		yes
pocketsphinx_zh.js:1 -ncep		13		13
pocketsphinx_zh.js:1 -nfft		512		512
pocketsphinx_zh.js:1 -nfilt		40		40
pocketsphinx_zh.js:1 -nwpen		1.0		1.000000e+00
pocketsphinx_zh.js:1 -pbeam		1e-48		1.000000e-48
pocketsphinx_zh.js:1 -pip		1.0		1.000000e+00
pocketsphinx_zh.js:1 -pl_beam	1e-10		1.000000e-10
pocketsphinx_zh.js:1 -pl_pbeam	1e-5		1.000000e-05
pocketsphinx_zh.js:1 -pl_window	0		0
pocketsphinx_zh.js:1 -rawlogdir			
pocketsphinx_zh.js:1 -remove_dc	no		no
pocketsphinx_zh.js:1 -remove_noise	yes		no
pocketsphinx_zh.js:1 -remove_silence	yes		yes
pocketsphinx_zh.js:1 -round_filters	yes		yes
pocketsphinx_zh.js:1 -samprate	16000		8.000000e+03
pocketsphinx_zh.js:1 -seed		-1		-1
pocketsphinx_zh.js:1 -sendump			
pocketsphinx_zh.js:1 -senlogdir			
pocketsphinx_zh.js:1 -senmgau			
pocketsphinx_zh.js:1 -silprob	0.005		5.000000e-03
pocketsphinx_zh.js:1 -smoothspec	no		no
pocketsphinx_zh.js:1 -svspec				
pocketsphinx_zh.js:1 -time		no		no
pocketsphinx_zh.js:1 -tmat				
pocketsphinx_zh.js:1 -tmatfloor	0.0001		1.000000e-04
pocketsphinx_zh.js:1 -topn		4		4
pocketsphinx_zh.js:1 -topn_beam	0		0
pocketsphinx_zh.js:1 -toprule			
pocketsphinx_zh.js:1 -transform	legacy		legacy
pocketsphinx_zh.js:1 -unit_area	yes		yes
pocketsphinx_zh.js:1 -upperf		6855.4976	6.855498e+03
pocketsphinx_zh.js:1 -usewdphones	no		no
pocketsphinx_zh.js:1 -uw		1.0		1.000000e+00
pocketsphinx_zh.js:1 -vad_postspeech	25		25
pocketsphinx_zh.js:1 -vad_prespeech	25		25
pocketsphinx_zh.js:1 -vad_threshold	2.0		2.000000e+00
pocketsphinx_zh.js:1 -var				
pocketsphinx_zh.js:1 -varfloor	0.0001		1.000000e-04
pocketsphinx_zh.js:1 -varnorm	no		no
pocketsphinx_zh.js:1 -verbose	no		no
pocketsphinx_zh.js:1 -warp_params			
pocketsphinx_zh.js:1 -warp_type	inverse_linear	inverse_linear
pocketsphinx_zh.js:1 -wbeam		7e-29		7.000000e-29
pocketsphinx_zh.js:1 -wip		0.65		6.500000e-01
pocketsphinx_zh.js:1 -wlen		0.025625	2.562500e-02
pocketsphinx_zh.js:1 
pocketsphinx_zh.js:1 INFO: cmd_ln.c(696): Parsing command line:
pocketsphinx_zh.js:1 \
pocketsphinx_zh.js:1 	-nfilt 20 \
pocketsphinx_zh.js:1 	-lowerf 1 \
pocketsphinx_zh.js:1 	-upperf 4000 \
pocketsphinx_zh.js:1 	-wlen 0.025 \
pocketsphinx_zh.js:1 	-transform dct \
pocketsphinx_zh.js:1 	-round_filters no \
pocketsphinx_zh.js:1 	-remove_dc yes \
pocketsphinx_zh.js:1 	-feat 1s_c_d_dd \
pocketsphinx_zh.js:1 	-svspec 0-12/13-25/26-38 \
pocketsphinx_zh.js:1 	-agc none \
pocketsphinx_zh.js:1 	-cmn current \
pocketsphinx_zh.js:1 	-cmninit 54,-1,2 \
pocketsphinx_zh.js:1 	-varnorm no 
pocketsphinx_zh.js:1 
pocketsphinx_zh.js:1 Current configuration:
pocketsphinx_zh.js:1 [NAME]		[DEFLT]		[VALUE]
pocketsphinx_zh.js:1 -agc		none		none
pocketsphinx_zh.js:1 -agcthresh	2.0		2.000000e+00
pocketsphinx_zh.js:1 -alpha		0.97		9.700000e-01
pocketsphinx_zh.js:1 -ceplen		13		13
pocketsphinx_zh.js:1 -cmn		current		current
pocketsphinx_zh.js:1 -cmninit	8.0		54,-1,2
pocketsphinx_zh.js:1 -dither		no		no
pocketsphinx_zh.js:1 -doublebw	no		no
pocketsphinx_zh.js:1 -feat		1s_c_d_dd	1s_c_d_dd
pocketsphinx_zh.js:1 -frate		100		100
pocketsphinx_zh.js:1 -input_endian	little		little
pocketsphinx_zh.js:1 -lda				
pocketsphinx_zh.js:1 -ldadim		0		0
pocketsphinx_zh.js:1 -lifter		0		0
pocketsphinx_zh.js:1 -logspec	no		no
pocketsphinx_zh.js:1 -lowerf		133.33334	1.000000e+00
pocketsphinx_zh.js:1 -ncep		13		13
pocketsphinx_zh.js:1 -nfft		512		512
pocketsphinx_zh.js:1 -nfilt		40		20
pocketsphinx_zh.js:1 -remove_dc	no		yes
pocketsphinx_zh.js:1 -remove_noise	yes		no
pocketsphinx_zh.js:1 -remove_silence	yes		yes
pocketsphinx_zh.js:1 -round_filters	yes		no
pocketsphinx_zh.js:1 -samprate	16000		8.000000e+03
pocketsphinx_zh.js:1 -seed		-1		-1
pocketsphinx_zh.js:1 -smoothspec	no		no
pocketsphinx_zh.js:1 -svspec				0-12/13-25/26-38
pocketsphinx_zh.js:1 -transform	legacy		dct
pocketsphinx_zh.js:1 -unit_area	yes		yes
pocketsphinx_zh.js:1 -upperf		6855.4976	4.000000e+03
pocketsphinx_zh.js:1 -vad_postspeech	25		25
pocketsphinx_zh.js:1 -vad_prespeech	25		25
pocketsphinx_zh.js:1 -vad_threshold	2.0		2.000000e+00
pocketsphinx_zh.js:1 -varnorm	no		no
pocketsphinx_zh.js:1 -verbose	no		no
pocketsphinx_zh.js:1 -warp_params			
pocketsphinx_zh.js:1 -warp_type	inverse_linear	inverse_linear
pocketsphinx_zh.js:1 -wlen		0.025625	2.500000e-02
pocketsphinx_zh.js:1 
pocketsphinx_zh.js:1 INFO: acmod.c(251): Parsed model-specific feature parameters from tdt_sc_8k/feat.params
pocketsphinx_zh.js:1 INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='current', VARNORM='no', AGC='none'
pocketsphinx_zh.js:1 INFO: cmn.c(143): mean[0]= 12.00, mean[1..12]= 0.0
pocketsphinx_zh.js:1 INFO: acmod.c(170): Using subvector specification 0-12/13-25/26-38
pocketsphinx_zh.js:1 INFO: mdef.c(517): Reading model definition: tdt_sc_8k/mdef
pocketsphinx_zh.js:1 INFO: mdef.c(530): Found byte-order mark BMDF, assuming this is a binary mdef file
pocketsphinx_zh.js:1 INFO: bin_mdef.c(336): Reading binary model definition: tdt_sc_8k/mdef
pocketsphinx_zh.js:1 INFO: bin_mdef.c(516): 70 CI-phone, 65021 CD-phone, 3 emitstate/phone, 210 CI-sen, 5210 Sen, 11271 Sen-Seq
pocketsphinx_zh.js:1 INFO: tmat.c(206): Reading HMM transition probability matrices: tdt_sc_8k/transition_matrices
pocketsphinx_zh.js:1 INFO: acmod.c(123): Attempting to use SCHMM computation module
pocketsphinx_zh.js:1 INFO: ms_gauden.c(198): Reading mixture gaussian parameter: tdt_sc_8k/means
pocketsphinx_zh.js:1 INFO: ms_gauden.c(292): 1 codebook, 3 feature, size: 
3pocketsphinx_zh.js:1 INFO: ms_gauden.c(294):  256x13
pocketsphinx_zh.js:1 INFO: ms_gauden.c(198): Reading mixture gaussian parameter: tdt_sc_8k/variances
pocketsphinx_zh.js:1 INFO: ms_gauden.c(292): 1 codebook, 3 feature, size: 
3pocketsphinx_zh.js:1 INFO: ms_gauden.c(294):  256x13
pocketsphinx_zh.js:1 INFO: ms_gauden.c(354): 0 variance values floored
pocketsphinx_zh.js:1 INFO: s2_semi_mgau.c(903): Loading senones from dump file tdt_sc_8k/sendump
pocketsphinx_zh.js:1 INFO: s2_semi_mgau.c(927): BEGIN FILE FORMAT DESCRIPTION
pocketsphinx_zh.js:1 INFO: s2_semi_mgau.c(1022): Using memory-mapped I/O for senones
pocketsphinx_zh.js:1 INFO: s2_semi_mgau.c(1296): Maximum top-N: 4 Top-N beams: 0 0 0
pocketsphinx_zh.js:1 INFO: dict.c(320): Allocating 4103 * 20 bytes (80 KiB) for word entries
pocketsphinx_zh.js:1 INFO: dict.c(342): Reading filler dictionary: tdt_sc_8k/noisedict
pocketsphinx_zh.js:1 INFO: dict.c(213): Allocated 0 KiB for strings, 0 KiB for phones
pocketsphinx_zh.js:1 INFO: dict.c(345): 7 words read
pocketsphinx_zh.js:1 INFO: dict2pid.c(396): Building PID tables for dictionary
pocketsphinx_zh.js:1 INFO: dict2pid.c(406): Allocating 70^3 * 2 bytes (669 KiB) for word-initial triphones
pocketsphinx_zh.js:1 INFO: dict2pid.c(132): Allocated 59080 bytes (57 KiB) for word-final triphones
pocketsphinx_zh.js:1 INFO: dict2pid.c(196): Allocated 59080 bytes (57 KiB) for single-phone word triphones
pocketsphinx_zh.js:1 ERROR: "pocketsphinx.c", line 816: No search module is selected, did you forget to specify a language model or grammar?

**Comment by syl22-00** [comment]
So, as you can see in the logs, it seems like the init parameters are not correct, it uses `-hmm tdt_sc_8k`, and no `-dict` and no `-lm` parameter. Is the output from a trial with different parameters than what you posted in the ticket?

Also, I'd suggest to add all files you want to lazy-load inside one lazyload command. Those messages are processed asynchronously so you should do your successive commands in the callbacks rather than posting messages one after the other.

**Comment by xinxu75** [comment]
Thanks Sylvain for your suggestions and diagnosis. 

Your observation is precisely what confuses me: I tried all the different ways to lazyload files under zh_broadcastnews_ptm256_8000 folder, zh_broadcastnews_utf8.dic and zh_broadcastnews_64000_utf8.DMP, however it seems they are never loaded and I always obtain the same error message.

As you suggested, I also put all the files and folders into a single lazyload command (but I'm not sure whether my way to append more folders and files within the "data: {...}" statement is correct, please correct me if I'm wrong), again the same error - see the attached live_lazyload.html which is basically a revised version of your live_zh.html demo, by lazyloading the folders/files rather than using wordList. This live_lazyload.html and all the folders/files to be loaded are put under ROOT/webapp/, where all the .js files are put under ROOT/webapp/js/.

Could you kindly suggest what may go wrong? This has been puzzling me for quite long and I still couldn't understand why. Your help is much appreciated.

------------------------------------------------------------------------

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>PocketSphinx.js in Chinese</title>
  </head>
  <body>
    <h2>PocketSphinx.js live demo for Chinese language</h2>
    <ul>
      <li>This demo works on recent versions of Chrome and Firefox with the Web Audio API, make sure it actually records audio (audio recording does not work well on all configs and platforms).</li>
      <li>Press "Start" and speak a few Chinese greetings.</li>
    </ul>
    
    <button id="startBtn">Start</button>
    <button id="stopBtn">Stop</button>
    <span id="recording-indicator" style="border-radius: 10px; -moz-border-radius: 10px; -webkit-border-radius: 10px; width: 20px; height: 20px; background: red;"></span>
    <h2>Recognition Output</h2>
    <div id="output" style="height:150px;overflow:auto;" >
    </div>
    <h2>Status</h2>
    <div id="current-status">Loading page</div>

    <script>
    var recognizer, recorder, callbackManager, audio_context;
    var isRecorderReady = isRecognizerReady = false;
    function postRecognizerJob(message, callback) {
      var msg = message || {};
      if(callbackManager) msg.callbackId = callbackManager.add(callback);
      if (recognizer) recognizer.postMessage(msg);
    };

    function spawnWorker(workerurl, onReady) {
        recognizer = new Worker(workerurl);
        recognizer.onmessage = function(event) {
          onReady(recognizer);
        };
        recognizer.postMessage('pocketsphinx_zh.js');
    };

    function updateHyp(hyp) {
      document.getElementById('output').innerHTML = hyp;
    };

    function updateUI() {
      if (isRecorderReady && isRecognizerReady) startBtn.disabled = stopBtn.disabled = false;
    };

    function updateStatus(newStatus) {
      document.getElementById('current-status').innerHTML += "<br/>" + newStatus;
    };

    function displayRecording(display) {
      if (display) document.getElementById('recording-indicator').innerHTML = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
      else document.getElementById('recording-indicator').innerHTML = "";
    };

    function startUserMedia(stream) {
      var input = audio_context.createMediaStreamSource(stream);
      window.firefox_audio_hack = input;
      // Notice that for this Chinese acoustic model, audio must be at 8kHz, so we should
      // request it from the recorder
      var audioRecorderConfig = {
             errorCallback: function(x) {updateStatus("Error from recorder: " + x);},
             outputSampleRate: 8000
      };
      recorder = new AudioRecorder(input, audioRecorderConfig);
      // If a recognizer is ready, we pass it to the recorder
      if (recognizer) recorder.consumers = [recognizer];
      isRecorderReady = true;
      updateUI();
      updateStatus("Audio recorder ready");
    };

    var startRecording = function() {
    //var id = document.getElementById('grammars').value;
    //if (recorder && recorder.start(id)) displayRecording(true);

    if (recorder && recorder.start()) displayRecording(true);
    };

    var stopRecording = function() {
      recorder && recorder.stop();
      displayRecording(false);
    };

    var recognizerReady = function() {
         //updateGrammars();
         isRecognizerReady = true;
         updateUI();
         updateStatus("Recognizer ready");
    };

/******************************* the below are no longer needed
    var updateGrammars = function() {
      var selectTag = document.getElementById('grammars');
      for (var i = 0 ; i < grammarIds.length ; i++) {
          var newElt = document.createElement('option');
          newElt.value=grammarIds[i].id;
          newElt.innerHTML = grammarIds[i].title;
          selectTag.appendChild(newElt);
      }                          
    };
    var feedGrammar = function(g, index, id) {
      if (id && (grammarIds.length > 0)) grammarIds[0].id = id.id;
      if (index < g.length) {
        grammarIds.unshift({title: g[index].title})
	  postRecognizerJob({command: 'addGrammar', data: g[index].g},
                           function(id) {feedGrammar(grammars, index + 1, {id:id});});
      } else {
        recognizerReady();
      }
    };
    var feedWords = function(words) {
         postRecognizerJob({command: 'addWords', data: words},
                      function() {feedGrammar(grammars, 0);});
    };
******************************/

    // This initializes the recognizer.
    var initRecognizer = function() {
        // You can pass parameters to the recognizer, such as : {command: 'initialize', data: [["-hmm", "my_model"], ["-fwdflat", "no"]]}
        // Pay attention here to state the sample rate as the default value is 16kHz and this Chinese acoustic model uses 8kHz
        postRecognizerJob({command: 'initialize', data:[
        	["-lm", "zh_broadcastnews_64000_utf8.DMP"],
        	["-dict", "zh_broadcastnews_utf8.dic"], 
        	["-samprate", "8000"], 
        	["-hmm", "zh_broadcastnews_ptm256_8000"],
        	["-fwdflat", "no"]
        	]},                          
        	function() {                                      
        		if (recorder) recorder.consumers = [recognizer];
        		recognizerReady();
                //feedWords(wordList);                
        	}	
        );
    };

    window.onload = function() {
      updateStatus("Initializing Web Audio and speech recognizer, waiting for approval to access your microphone");
      callbackManager = new CallbackManager();
      spawnWorker("js/recognizer.js", function(worker) {
          worker.onmessage = function(e) {
              if (e.data.hasOwnProperty('id')) {
                var clb = callbackManager.get(e.data['id']);
                var data = {};
                if( e.data.hasOwnProperty('data')) data = e.data.data;
                if(clb) clb(data);
              }
              if (e.data.hasOwnProperty('hyp')) {
                var newHyp = e.data.hyp;
                var newHypChinese = e.data.hyp.split(' ').map(function(x) {return wordListChinese[x];}).join(' ');
                if (e.data.hasOwnProperty('final') &&  e.data.final) {
                    newHyp = "Final: " + newHyp;
                    newHypChinese = "Final: " + newHypChinese;
                }
                updateHyp(newHyp + '<br><br>' + newHypChinese);
              }
              if (e.data.hasOwnProperty('status') && (e.data.status == "error")) {
                updateStatus("Error in " + e.data.command + " with code " + e.data.code);
              }
          };
          postRecognizerJob({command: 'lazyLoad',
              data: {folders: [["/", "zh_broadcastnews_ptm256_8000"]], 
            	  files: [["/zh_broadcastnews_ptm256_8000", "means", "../zh_broadcastnews_ptm256_8000/means"],
        			  ["/zh_broadcastnews_ptm256_8000", "variances", "../zh_broadcastnews_ptm256_8000/variances"],
        			  ["/zh_broadcastnews_ptm256_8000", "transition_matrices", "../zh_broadcastnews_ptm256_8000/transition_matrices"],		       
        			  ["/zh_broadcastnews_ptm256_8000", "sendump", "../zh_broadcastnews_ptm256_8000/sendump"],		       
        			  ["/zh_broadcastnews_ptm256_8000", "mdef", "../zh_broadcastnews_ptm256_8000/mdef"],		       
        			  ["/zh_broadcastnews_ptm256_8000", "feat.params", "../zh_broadcastnews_ptm256_8000/feat.params"],		       
        			  ["/zh_broadcastnews_ptm256_8000", "mixture_weights", "../zh_broadcastnews_ptm256_8000/mixture_weights"],		       
        			  ["/zh_broadcastnews_ptm256_8000", "noisedict", "../zh_broadcastnews_ptm256_8000/noisedict"]],
        			  folders: [], 
        			  files: [["/", "zh_broadcastnews_utf8.dic", "../zh_broadcastnews_utf8.dic"],["/", "zh_broadcastnews_64000_utf8.DMP", "../zh_broadcastnews_64000_utf8.DMP"]]}
          }, initRecognizer);
      });
      try {
        window.AudioContext = window.AudioContext || window.webkitAudioContext;
        navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
        window.URL = window.URL || window.webkitURL;
        audio_context = new AudioContext();
      } catch (e) {
        updateStatus("Error initializing Web Audio browser");
      }
      if (navigator.getUserMedia) navigator.getUserMedia({audio: true}, startUserMedia, function(e) {
                                      updateStatus("No live audio input in this browser");
                                  });
      else updateStatus("No web audio support in this browser");

    var startBtn = document.getElementById('startBtn');
    var stopBtn = document.getElementById('stopBtn');
    startBtn.disabled = true;
    stopBtn.disabled = true;
    startBtn.onclick = startRecording;
    stopBtn.onclick = stopRecording;
    };

    // This is the list of words that need to be added to the recognizer
    // This follows the CMU dictionary format and the phone set of the Chinese model
    // These words were taken from model/lm/zh_CN/mandarin_notone.dic
//    var wordList =;
//    var wordListChinese = ;
//    var grammarChineseGreetings =;
//    var grammars = [{title: "Chinese Greetings", g: grammarChineseGreetings}];
//    var grammarIds = [];
    </script>
    
    <script src="js/audioRecorder.js"></script>
    <script src="js/callbackManager.js"></script>
  </body>
</html>

**Comment by xinxu75** [comment]
Hi Sylvain,

As I couldn't make "lazyLoad" work, I tried another approach "Using packaged JavaScript files" described in README, using "load" command. However, I found the following problems:

1. If I packaged the SLM "zh_broadcastnews_64000_utf8.DMP", which is 213MB, into a JavaScript file, the .js file is now 871MB. When I tried to "load" this lm together with dict and acoustic model, Chrome simply crashed when loading them, without any error message.
I also tried to search for other smaller Chinese lm/dict, but this appears to be the only official Chinese lm/dict for CMUSphinx?

2. If I omitted lm/dict and only loaded the acoustic model "zh_broadcastnews_ptm256_8000", then I got precisely the same problem as before (console outputs are identical as previously provided): the model "tdt_sc_8k" was loaded (I guess this is the default one for pocketSphinx_zh.js ?), and the error persists - 
ERROR: "pocketsphinx.c", line 816: No search module is selected, did you forget to specify a language model or grammar?

I attached my command for packaging and code snippet of loading. If you could kindly provide some hints or suggestions where I did wrong or what alternative ways to try, that would be much appreciated.

Thanks a lot

-----------------------------------
1. emscripten packaging command (This part works, I got .js files, although zh_lm.js is 871MB): In the "ROOT\webapp\js" folder, I ran the following commands

python ...path\to\emsdk-portable-64bit\emscripten\1.37.21\tools\file_packager.py pocketsphinx_zh.js --embed zh_broadcastnews_ptm256_8000\means --js-output=zh_broadcastnews_ptm256_8000_js\means.js
... ...
... ...
python ...path\to\emsdk-portable-64bit\emscripten\1.37.21\tools\file_packager.py pocketsphinx_zh.js --embed zh_broadcastnews_ptm256_8000\noisedict --js-output=zh_broadcastnews_ptm256_8000_js\noisedict.js

python ...path\to\emsdk-portable-64bit\emscripten\1.37.21\tools\file_packager.py pocketsphinx_zh.js --embed zh_broadcastnews_utf8.dic --js-output=zh_dict.js
python ...path\to\emsdk-portable-64bit\emscripten\1.37.21\tools\file_packager.py pocketsphinx_zh.js --embed zh_broadcastnews_64000_utf8.DMP --js-output=zh_lm.js


2. Within spawnWorker():

          postRecognizerJob({command: 'load',
              data: ["zh_broadcastnews_ptm256_8000_js/mdef.js",
            	  "zh_broadcastnews_ptm256_8000_js/means.js",
            	  "zh_broadcastnews_ptm256_8000_js/transition_matrices.js",
            	  "zh_broadcastnews_ptm256_8000_js/sendump.js",
            	  "zh_broadcastnews_ptm256_8000_js/feat_params.js",
            	  "zh_broadcastnews_ptm256_8000_js/mixture_weights.js",
            	  "zh_broadcastnews_ptm256_8000_js/noisedict.js",
                  "zh_broadcastnews_ptm256_8000_js/variances.js",
                  "zh_dict.js",
                  "zh_lm.js"
                  ]
          }, initRecognizer);   


3. initRecognizer() - Chrome crashed even before it reached here

    var initRecognizer = function() {
        postRecognizerJob({command: 'initialize', data:[
        	["-hmm", "zh_broadcastnews_ptm256_8000_js"],
        	["-fwdflat", "no"],
        	["-dict", "zh_broadcastnews_utf8.dic"],    
        	["-lm", "zh_broadcastnews_64000_utf8.DMP"],
        	["-samprate", "8000"]
        	]},                          
        	function() {                                      
        		if (recorder) recorder.consumers = [recognizer];
        		recognizerReady();            
        	}	
        );
    };

**Comment by syl22-00** [comment]
In any case, I don't think a large statistical language model would give you acceptable performance in a browser. If that can be enough for your application, try making grammars instead.
Lazy loading models is for sure a better approach than compiling into JavaScript, especially now with webassembly. If you still have issues with lazy loading files, feel free to post more infos and reopen the ticket.
