### ISSUE TITLE
pocketsphinx.wasm update

### ISSUE THREAD

**Issue by norzak** [syl22-00/pocketsphinx.js#115]
could you also build pocketsphinx.wasm together with javascript version into https://github.com/syl22-00/pocketsphinx.js/tree/master/webapp/js ? just a thought. thanks.

**Comment by syl22-00** [comment]
It is indeed already compiled in wasm, the live demo and the test suite already use the WebAssembly version.

**Comment by norzak** [comment]
Ok thanks
