### ISSUE TITLE
The english live demo is spitting out nonsensical results.

### ISSUE THREAD

**Issue by viziionary** [syl22-00/pocketsphinx.js#123]
See a video example of wild results: https://www.useloom.com/share/469615e969154a369ae18db5663b7381

This is the live demo so there's nothing non-standard involved.

**Comment by viziionary** [comment]
Also tested in firefox.

**Comment by syl22-00** [comment]
I wont say your video shows nonsensical results but results are indeed not good. There are several things to understand:

* If this was your first recording after initialization, you might get more satisfactory results for the second and upcoming attempts as CMN kicks in.
* This demo uses a tiny acoustic model. For real life applications, you would probably choose a larger one. There are free available ones, and resources to build your own on cmusphinx website.
* The "digits" grammar is just a loop over all digits without prior probabilities on the more likely sequences, so confusions are likely. If you try another grammar from the drop down menu, you'll see better results. Depending on your own target application, you'll hopefully have grammars with more constrains.
* Pocketsphinx, hence Pocketsphinx.js, is a generation old-engine, you should not expect performance similar to kaldi or the latest commercial recognizers.

**Comment by TrRavi** [comment]
@syl22-00 ,
Sir if your are saying "Pocketsphinx.js, is a generation old-engine,". 
i agree with it . 
can you tell me what is new one .. 
I want to implement offline speech  recognition .
Thanks
