### ISSUE TITLE
Not able to recognize speech properly even after using custom AM and LM.

### ISSUE THREAD

**Issue by GitPiyush** [syl22-00/pocketsphinx.js#13]
i have created custom pocketsphinx javascript file on my windows machine, as per the steps mentioned and customized Live demo page to check the accuracy of the Dictionary. Very strange result, it is not recognizing speech properly and getHyp is returning any word present in dictionary.
i have shared all the related documents @https://drive.google.com/folderview?id=0B0cJA2S9BX4MX0FldlZ1S3lxczQ&usp=sharing . 
zip contains created pocketsphinx, AM,LM, Dictionary and customized Live demo page.
Can you please look into the issue and let me know what i am missing here.

**Comment by VBR1016** [comment]
Hi every body!
I installed pocketsphinx in windows and I run it with the programm in Github.
but it doe'nt recognise any word correctly??
what should I do?
and I don't know how to use "sphinx_lm_convert -i ECL_Vocab.lm -o ECL_Vocab.DMP"
if my problem is it. please help me.
Thank you.

**Comment by syl22-00** [comment]
@VBR1016 This is the `pocketsphinx.js` repository, you should probably ask your question directly in https://github.com/cmusphinx
