### ISSUE TITLE
Words.push_back accept 1 arguments only

### ISSUE THREAD

**Issue by tlkiong** [syl22-00/pocketsphinx.js#134]
According to the doc (readme), to add words, do the following:

```
words.push_back(["HELLO", "HH AH L OW"], ["HELLO(2)", "HH EH L OW"]);
```

However, running that seems to give me the error:

```
"function VectorWords.push_back called with 2 arguments, expected 1 args!"
```

Is the doc wrong?

**Comment by syl22-00** [comment]
Thanks @tlkiong , you are correct, the doc is wrong.
