### ISSUE TITLE
BindingError with self-compiled pocketsphinx.js

### ISSUE THREAD

**Issue by bene51** [syl22-00/pocketsphinx.js#136]
I followed the README to compile pocketsphinx.js myself:
`$ cd pocketsphinx.js && mkdir build && cd build`
`$ cmake -DEMSCRIPTEN=1 -DCMAKE_TOOLCHAIN_FILE=../emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake ..`
`Copying /home/bschmid/pocketsphinx.js/am/rm1_200 to binary dir`
`-- Configuring done`
`-- Generating done`
`-- Build files have been written to: /home/bschmid/pocketsphinx.js/build`
`$ make`

There were a couple of warnings:
`shared:WARNING: Assuming object file output in the absence of `-c`, based on output filename. Please add with `-c` or `-r` to avoid this warning`
`shared:WARNING: ignoring unsupported linker flag: `-soname``
`shared:WARNING: ignoring unsupported linker flag: `libpocketsphinx.so``
`shared:WARNING: When Emscripten compiles to a typical native suffix for shared libraries (.so, .dylib, .dll) then it emits an object file. You should then compile that to an emscripten SIDE_MODULE (using that flag) with suffix .wasm (for wasm) or .js (for asm.js). (You may also want to adapt your build system to emit the more standard suffix for a an object file, '.bc' or '.o', which would avoid this warning.)`

and lots of 
`wasm-ld: warning: unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB: existing=268 expected=269`

The full output of make can be found here:
https://pastebin.com/evn2bkRs

I copied the built pocketsphinx.js and pocketsphinx.wasm to the webapp/js/ folder and then run the local webserver as described in the README, and when I open http://localhost:8000/webapp/live.html in a browser, I get a BindError:
`BindingError {name: "BindingError", message: "No dynCall invoker for signature: IS2_EEEE", stack: "BindingError: No dynCall invoker for signature: IS…calhost:8000/webapp/js/pocketsphinx.js:1:3099759)"`

I compiled both on Windows and Linux, but the result was in both cases identical.

Using pocketsphinx.js and pocketsphinx.wasm from the git repository works nicely.

Any help would be greatly appreciated

**Comment by bene51** [comment]
I answer my own question:

Emscripten has two possible backends, upstream and fastcomp. I previously installed Emscripten as described on their homepage:
`$ git clone https://github.com/emscripten-core/emsdk.git`
`$ cd emsdk`
`$ ./emsdk install latest && ./emsdk activate latest`

If I replace the last line with
`$ ./emsdk install latest-fastcomp && ./emsdk activate latest-fastcomp`

compilation works and I can load the sample page in the browser without getting above described BindingError

**Comment by yafesdev** [comment]
This seems to be a recent issue, as the default was `fastcomp` for a long time, it was just changed later to `upstream` to be the default.
