### ISSUE TITLE
-kws_threshold is an unknown argument / doesn't actually change the threshold?

### ISSUE THREAD

**Issue by T045T** [syl22-00/pocketsphinx.js#14]
If I set -kws_threshold to any value, I get the following console output:

```
ERROR: "cmd_ln.c", line 945: Unknown argument: -kws_threshold js/pocketsphinx.js:150
INFO: kws_search.c(291): KWS(beam: -1080, plp: -23, threshold -524288)
```

It feels like the threshold actually doesn't change, i.e. it's not just an output glitch.
If it isn't set, the threshold in the output is 0, and the keyword is never detected.

Of course, this might be an upstream bug, seeing how new kws is, but I can't natively test pocketsphinx at the moment :(

**Comment by willadamskeane** [comment]
I'm having this issue as well - is there any way to actually set the -kws-threshold?
