### ISSUE TITLE
Grammar for numbers?

### ISSUE THREAD

**Issue by getify** [syl22-00/pocketsphinx.js#145]
I have a webapp where the only input I need to recognize is numeric input, such as speaking "eleven", "thirty seven", etc, and having those come in as "11", "37", etc. I'm using the built-in [SpeechRecognition](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition) API with it's regular english grammar. If you speak "eleven" or "thirty seven", it very reliably comes through as "11" and "37". I additionally have basic logic in there to recognize and convert some phonetic homophones, like "won" (for "1"), "for" (for "4"), "ate" (for "8"), etc. But then I just filter out any other recognized input that's not numbers. This all works well.

But this built-in API isn't present in Safari (desktop or iOS), so I was hoping to use pocketsphinx.js (sort of like a polyfill) as a backup option for those browsers. But off the bat, it seems like a lack of "number" grammar may be pretty limiting. I see there's a grammar for digits, but is there a grammar for recognizing numbers (like speaking "eleven" instead of having to speak "one one")?

Also, in the demo webpage, when I pick the "digits" grammar and click "start", even if I'm not speaking, the demo starts spitting out digits ("eight", "two", etc) just from ambient room noise... so it seems like it's awfully over-sensitive or trying way too hard with the grammar to coerce every single latent sound into one of the digits.

Any suggestions on what I need to do here? Is there tuning I can perform to reduce the false positives? Is there a way to get a grammar more well-suited for numeric input?

**Comment by getify** [comment]
Another reason for wanting pocketsphinx.js, btw: the `SpeechRecognition` API only works "online" (meaning it uses external google servers), so I could in theory fall back to this library when offline. Would really like to figure out a way to make this work as a backup.

**Comment by Kaljurand** [comment]
This reminds me an old project of mine: https://github.com/Kaljurand/touchless-timer. It contains a grammar for alarm clock expressions, whose subgrammar covers numbers. The grammars were implemented in Grammatical Framework (https://www.grammaticalframework.org/). The demo (https://touchless-timer.appspot.com/timer/en.html) still works, but is also over-sensitive to background noise (I don't know a solution for that).

**Comment by getify** [comment]
Extrapolating from the pocketsphinx.js web demo (and looking up the CMU pronunciations), I've so far got this:

```js
var wordList = [
    ["NEGATIVE","N EH G AH T IH V"],
    ["O", "OW"],
    ["ZERO", "Z IH R OW"],
    ["ONE", "W AH N"],
    ["TWO", "T UW"],
    ["THREE", "TH R IY"],
    ["FOUR", "F AO R"],
    ["FIVE", "F AY V"],
    ["SIX", "S IH K S"],
    ["SEVEN", "S EH V AH N"],
    ["EIGHT", "EY T"],
    ["NINE", "N AY N"],
    ["TEN", "T EH N"],
    ["ELEVEN", "IH L EH V AH N"],
    ["TWELVE", "T W EH L V"],
    ["THIRTEEN", "TH ER T IY N"],
    ["FOURTEEN", "F AO R T IY N"],
    ["FIFTEEN", "F IH F T IY N"],
    ["SIXTEEN", "S IH K S T IY N"],
    ["SEVENTEEN", "S EH V AH N T IY N"],
    ["EIGHTEEN", "EY T IY N"],
    ["NINETEEN", "N AY N T IY N"],
    ["TWENTY", "T W EH N T IY"],
    ["THIRTY", "TH ER D IY"],
    ["FORTY", "F AO R T IY"],
    ["FIFTY", "F IH F T IY"],
    ["SIXTY", "S IH K S T IY"],
    ["SEVENTY", "S EH V AH N T IY"],
    ["EIGTHY", "EY T IY"],
    ["NINETY", "N AY N T IY"],
    ["HUNDRED", "HH AH N D R AH D"],
    ["THOUSAND", "TH AW Z AH N D"],
    ["MILLION", "M IH L Y AH N"],
    ["BILLION", "B IH L Y AH N"],
    ["TRILLION", "T R IH L Y AH N"],
    ["QUADRILLION", "K W AA D R IH L Y AH N"],
    ["A","EY"],
    ["A(2)","AH"],
    ["AND", "AE N D"],
    ["AND(2)", "AH N D"],
    ["POINT", "P OY N T"],
    ["DOT", "D AA T"],
    ["DOZEN","D AH Z AH N"],
    ["SCORE","S K AO R"],
    ["PAIR","P EH R"],
];
```

But I don't know how to add those additional words into this grammar definition so that you can speak compound numbers:

```js
var grammarDigits = {
    numStates: 1,
    start: 0,
    end: 0,
    transitions: [{
        from: 0,
        to: 0,
        word: "ONE"
    }, {
        from: 0,
        to: 0,
        word: "TWO"
    }, {
        from: 0,
        to: 0,
        word: "THREE"
    }, {
        from: 0,
        to: 0,
        word: "FOUR"
    }, {
        from: 0,
        to: 0,
        word: "FIVE"
    }, {
        from: 0,
        to: 0,
        word: "SIX"
    }, {
        from: 0,
        to: 0,
        word: "SEVEN"
    }, {
        from: 0,
        to: 0,
        word: "EIGHT"
    }, {
        from: 0,
        to: 0,
        word: "NINE"
    }, {
        from: 0,
        to: 0,
        word: "ZERO"
    }]
};
```

Is there somewhere that describes this grammar format so I could figure out how to define the additional words/transitions?

Any suggestions for next steps?

**Comment by getify** [comment]
Or maybe I'm overthinking this? Do I just need all those individual words added just like the digits? I just see like the OS's grammar demo has a bunch of states and transitions, so I was assuming I needed something like that here?

```js
var grammarNumbers = {
    numStates: 1,
    start: 0,
    end: 0,
    transitions: [{
        from: 0,
        to: 0,
        word: "NEGATIVE"
    }, {
        from: 0,
        to: 0,
        word: "O"
    }, {
        from: 0,
        to: 0,
        word: "ZERO"
    }, {
        from: 0,
        to: 0,
        word: "ONE"
    }, {
        from: 0,
        to: 0,
        word: "TWO"
    }, {
        from: 0,
        to: 0,
        word: "THREE"
    }, {
        from: 0,
        to: 0,
        word: "FOUR"
    }, {
        from: 0,
        to: 0,
        word: "FIVE"
    }, {
        from: 0,
        to: 0,
        word: "SIX"
    }, {
        from: 0,
        to: 0,
        word: "SEVEN"
    }, {
        from: 0,
        to: 0,
        word: "EIGHT"
    }, {
        from: 0,
        to: 0,
        word: "NINE"
    }, {
        from: 0,
        to: 0,
        word: "TEN"
    }, {
        from: 0,
        to: 0,
        word: "ELEVEN"
    }, {
        from: 0,
        to: 0,
        word: "TWELVE"
    }, {
        from: 0,
        to: 0,
        word: "THIRTEEN"
    }, {
        from: 0,
        to: 0,
        word: "FOURTEEN"
    }, {
        from: 0,
        to: 0,
        word: "FIFTEEN"
    }, {
        from: 0,
        to: 0,
        word: "SIXTEEN"
    }, {
        from: 0,
        to: 0,
        word: "SEVENTEEN"
    }, {
        from: 0,
        to: 0,
        word: "EIGHTEEN"
    }, {
        from: 0,
        to: 0,
        word: "NINETEEN"
    }, {
        from: 0,
        to: 0,
        word: "TWENTY"
    }, {
        from: 0,
        to: 0,
        word: "THIRTY"
    }, {
        from: 0,
        to: 0,
        word: "FORTY"
    }, {
        from: 0,
        to: 0,
        word: "FIFTY"
    }, {
        from: 0,
        to: 0,
        word: "SIXTY"
    }, {
        from: 0,
        to: 0,
        word: "SEVENTY"
    }, {
        from: 0,
        to: 0,
        word: "EIGHTY"
    }, {
        from: 0,
        to: 0,
        word: "NINETY"
    }, {
        from: 1,
        to: 2,
        word: "HUNDRED"
    }, {
        from: 1,
        to: 2,
        word: "THOUSAND"
    }, {
        from: 1,
        to: 2,
        word: "MILLION"
    }, {
        from: 1,
        to: 2,
        word: "BILLION"
    }, {
        from: 1,
        to: 2,
        word: "TRILLION"
    }, {
        from: 1,
        to: 2,
        word: "QUADRILLION"
    }, {
        from: 0,
        to: 0,
        word: "A"
    }, {
        from: 0,
        to: 0,
        word: "A(2)"
    }, {
        from: 0,
        to: 0,
        word: "AND"
    }, {
        from: 0,
        to: 0,
        word: "POINT"
    }, {
        from: 0,
        to: 0,
        word: "DOT"
    }, {
        from: 0,
        to: 0,
        word: "DOZEN"
    }, {
        from: 0,
        to: 0,
        word: "SCORE"
    }, {
        from: 0,
        to: 0,
        word: "PAIR"
    }]
};
```

Maybe that's enough?

I suppose also I'll need to write patterns that turn the words (like "two hundred forty three") into numerical form ("243"), right?

**Comment by getify** [comment]
Solution for the latter part, converting English number sentences ("one hundred forty two") to numbers ("142"):

https://gist.github.com/getify/83e6fae8f54c1d38f89132a130493f98
