### ISSUE TITLE
Using pocketsphinx.js with node.js outside of a browser?

### ISSUE THREAD

**Issue by jdevelvis** [syl22-00/pocketsphinx.js#2]
First, I want to thank you tremendously for porting pocketsphinx to Javascript! I'm currently working on a node.js project that will use pocketsphinx. But my knowledge of python is very basic, so I was searching for a node.js module/wrapper, and found this!

But before I dig in, I want to make sure this will work outside of a browser, using node.js. If I'm reading the README correctly, I can use the pocketsphinx.js and related files, but I'm on my own to modify the recognizer.js code to fit what I'm doing (or replace it altogether) as it's built to use browser objects. Is that correct? Or would I be better off going back to using the regular version of pocketsphinx?

**Comment by jaxcore** [comment]
This is a really good idea.  Before I go ahead and duplicate anyone's work, has anyone actually successfully done this?
