### ISSUE TITLE
Excessive resource use after 'stop' is called

### ISSUE THREAD

**Issue by jugg1es** [syl22-00/pocketsphinx.js#41]
My web application listens to the user speak.  When it recognizes a phrase, recognition is stopped, then it loads an MP4 into a video tag and plays it.  The user might do this 50 times in one session, speak -> stop recog -> play video -> start recog

The clips might be anywhere from 2 seconds to 20.  The issue I'm having is that after about 5 seconds of video playback, the video starts behaving like the audio is out of sync and jittery (like you would see if you were doing a lot of CPU intensive background tasks).  If I turn off speech, it does't happen.  It's clear that the performance hit is coming from something that the speech recognizer is doing, but the recognizer is clearly stopped.  

What can I do to address this?   Is there a way to completely halt all processing temporarily?

**Comment by syl22-00** [comment]
I don't have time to dig into it now, but I am guessing it could come from the recording process still running, resampling the signal and filling in the recording buffer, although this buffer is not sent to the recognizer. Is should be in `webapp/js/audioRecorder.js` and `webapp/js/audioRecorderWorker.js`.

**Comment by syl22-00** [comment]
Actually my guess was wrong, once recognition is stopped, there is no resampling going on. So I can't reproduce your issue. Is there some code you can share where we can see what is going on?

**Comment by jugg1es** [comment]
Yea, it doesn't appear to be anything specifically with pocketsphinx.  The problem doesn't happen on beefy machines.  I couldn't find anything that was running after stop was called.  The web app is very memory intensive already, so I'm chalking this down to machine resources.  Thanks anyway for your help.
