### ISSUE TITLE
Pipe data from sox

### ISSUE THREAD

**Issue by aequasi** [syl22-00/pocketsphinx.js#42]
Trying to find some documentation on this, but im not sure if its possible.

Can I pipe data from sox into the recognizer? I'm trying but i keep getting errors like "Cannot convert (bunch of random chars, looks like the buffer)"

**Comment by syl22-00** [comment]
I am not sure I am getting your point. Sox is a software written in C, running in the terminal, used to convert, record and process audio files. Are you saying you'd like to turn it into a JavaScript library, just like pocketsphinx.js?

Or if your question is how to pipe audio recorded by sox to pocketsphinx, on a native application, then you'd rather consult pocketsphinx people. I think there is a [library](http://sox.sourceforge.net/libsox.html) associated with sox that you can build on and process audio buffers before sending them to pocketsphinx.
