### ISSUE TITLE
Can pocketsphinx work on Andriod, IOS and  browsers other than Chrome and Firefox

### ISSUE THREAD

**Issue by JohnAReid** [syl22-00/pocketsphinx.js#43]
I am really interested in using pocketsphinx - but the examples only show Chrome and Firefox - so my question is can it work with other systems such and Android and IOS?

My thoughts are that if the system allows js in the client then it should work - or is there something I am missing?

**Comment by syl22-00** [comment]
pocketsphinx.js works on Chrome, Firefox, Opera, no matter on which operating system the browser runs. If you are targeting a native application, look at [pocketsphinx](http://cmusphinx.sourceforge.net/).
Or to be more accurate, the audio recording component of pocketsphinx.js works on these browsers only, but if you get the audio data from something else than getUserMedia, then you can use pocketsphinx.js on other browsers (Internet Explorer, Safari) or node.js.

**Comment by JohnAReid** [comment]
Many thanks - that is exactly what I wanted to know!
