### ISSUE TITLE
It does not work compilation

### ISSUE THREAD

**Issue by cybermaxik** [syl22-00/pocketsphinx.js#47]
It does not work compilation? Help me, please!
![pic](https://cloud.githubusercontent.com/assets/16693890/12311288/4f595b34-ba67-11e5-96f3-d1c6b836c587.png)

**Comment by syl22-00** [comment]
You're right, I don't know why this came through. It is a bug because of a recent change in pocketsphinx API, it should be fixed now.

**Comment by syl22-00** [comment]
I pushed the fix.
