### ISSUE TITLE
Erros compilation

### ISSUE THREAD

**Issue by cybermaxik** [syl22-00/pocketsphinx.js#48]
Help me, please! Errors (toString) when compiling with -DHMM_BASE, -DHMM_FOLDERS. Output file size pocketsphinx.js - 800Kb

![222](https://cloud.githubusercontent.com/assets/16693890/12326855/3ac100aa-bae4-11e5-83b1-51b0de7c5d25.png)

**Comment by syl22-00** [comment]
Please provide more context and copy/paste code rather than put a screenshot.

I am guessing your issue is because you are trying to package large files which are over the limit (see https://github.com/nodejs/node/issues/3175). If that's the case, there might be ways to reduce the file sizes. Anyways, please provide steps to reproduce your issue.

**Comment by cybermaxik** [comment]
cmake -G "MinGW Makefiles" -DEMSCRIPTEN=1 -DCMAKE_TOOLCHAIN_FILE=Emscripten.cmake -DHMM_BASE=models -DHMM_FOLDERS=model ..

Size folder "model" - 70Mb

Model: feat.params -1 Kb, feature_transform - 5 Kb, mdef - 7 Mb, means - 30 MB, mixture_weights - 1 Mb, noisedict - 1 Kb, transition_matrices - 3 Kb, variances - 30 Mb

**Comment by syl22-00** [comment]
With such a large model, you'd better put it outside the main JavaScript file. I guess the file is too large that's why packaging fails. It is explained here:
https://github.com/syl22-00/pocketsphinx.js#ii-package-model-files-outside-the-main-javascript

**Comment by cybermaxik** [comment]
Thank you. It is necessary to compile all the files? How .lm and .dic files compiled in js?

**Comment by cybermaxik** [comment]
How to fix errors "BindingError: String has UTF-16 code units that do not fit in 8 bits"?

**Comment by cybermaxik** [comment]
syl22-00, how to reduce the threshold, please tell me?

**Comment by syl22-00** [comment]
What threshold are you talking about? Again, you should provide context and steps to reproduce your issues if you want somebody to be able to help you.

**Comment by syl22-00** [comment]
Assuming there is issue left.
