### ISSUE TITLE
mandarin_notone.dic

### ISSUE THREAD

**Issue by resle** [syl22-00/pocketsphinx.js#49]
I am fiddling with Mandarin recognition, and in the webapp sample I found a reference to 
"model/lm/zh_CN/mandarin_notone.dic".

I have been searching for this file on the CMU Sphinx repository and elsewhere but I can't seem to find it anywhere.

Two questions: 
- could anyone point me to where I could download that from?
- given the "notone" part of the filename, I assume a "mandain_tone.dic" exists as well?

Thanks

**Comment by syl22-00** [comment]
Non-English models have apparently been taken out of the pocketsphinx repository. You can find then on Sphinx Sourceforge page:
http://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/

My understanding is that it is common practice to ignore tones in Chinese acoustic models. Also sphinxbase feature extraction does not get f0. There is a pitch extraction module, but I don't think it is used anywhere.

Those questions would get more valuable answers if you ask them on Sphinx forums/mailing lists/IRC, check out http://cmusphinx.sourceforge.net/

**Comment by resle** [comment]
Unfortunately mandarin_notone.dic has disappeared from the Sphinx repository too. I will ask on the mailing list, however if you happen to have preserved a copy and can make it available, it would help a lot.

Thanks again
a.

**Comment by syl22-00** [comment]
Chinese acoustic and language models, and the associate dictionary, are there, just with different file names:

* http://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Mandarin%20Language%20Model/
* http://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Mandarin%20Broadcast%20News%20acoustic%20models/

**Comment by resle** [comment]
Thanks, works flawlessly. The bizarre name confused me, but it is indeed what I was looking for
