### ISSUE TITLE
Implementing pocketsphinx.js

### ISSUE THREAD

**Issue by AbiramRM** [syl22-00/pocketsphinx.js#59]
Hey.. I know this is silly, I need help to make pocketsphix.js work after downloading it from the official website. I tried to run it as-it-is and did not work. I changed the 'src' to windows style. How do I go about it? @syl22-00

**Comment by syl22-00** [comment]
You need to provide more context about what you tried to do, where and how it failed.

**Comment by syl22-00** [comment]
Not enough details, please re-open with more infos.
