### ISSUE TITLE
function record in audioRecorderWorker.js 

### ISSUE THREAD

**Issue by JohnAReid** [syl22-00/pocketsphinx.js#78]
Working through the web example I have a question regarding the following code:

```
function record(inputBuffer){
    var isSilent = true;
    for (var i = 0 ; i < inputBuffer[0].length ; i++) {
	recBuffers.push((inputBuffer[0][i] + inputBuffer[1][i]) * 16383.0);
    }
    while(recBuffers.length * outputSampleRate / inSampleRate > outputBufferLength) {
	var result = new Int16Array(outputBufferLength);
	var bin = 0,
	num = 0,
	indexIn = 0,
	indexOut = 0;
	while(indexIn < outputBufferLength) {
	    bin = 0;
	    num = 0;
	    while(indexOut < Math.min(recBuffers.length, (indexIn + 1) * inSampleRate / outputSampleRate)) {
		bin += recBuffers[indexOut];
		num += 1;
		indexOut++;
	    }
	    result[indexIn] = bin / num;
	    if(isSilent && (result[indexIn] != 0)) isSilent = false;
	    indexIn++;
	}
	var output = {};
	output.command = 'newBuffer';
	output.data = result;
	if (isSilent) output.error = "silent";
	this.postMessage(output);
	recBuffers = recBuffers.slice(indexOut);
    }
}
```
My concern is that I think the final bit of the recBuffers (i.e. the amount less 4000)  does not get converted and therefore is not passed to the recognizer.

I hope there is something I missed!

Also could you explain the reason behind the line
`(inputBuffer[0][i] + inputBuffer[1][i]) * 16383.0`

**Comment by syl22-00** [comment]
You are very correct that the last buffer is dropped (max length 4000 samples, so 0.25 seconds for a typical 16kHz audio). In a real application, you'd want to continue actual recording until last buffer is full and passed to recognizer.

As for the line you pointed out, it converts the possibly stereo input with samples between -1 and 1 into mono PCM samples (signed short integers).

**Comment by JohnAReid** [comment]
Thanks for the quick reply - I assume I could pad out the final buffer with 0's to make it up to 
4000.

**Comment by syl22-00** [comment]
Right, but you might rather use very small and random numbers instead, there might be some artefacts with exactly 0 (dithering).

**Comment by JohnAReid** [comment]
Thanks @syl22-00 I have taken your advice and simply extended the recording activity by adding a timeout to the code:

from:
 ```
 var stopRecording = function() {
        recorder && recorder.stop();
        displayRecording(false);
      };
```

to: 

```
  var stopRecording = function() {
    setTimeout(function(){
      recorder && recorder.stop();
      displayRecording(false);
    }, 300);
   };
```
