### ISSUE TITLE
Multiply keywords recognised for each buffer

### ISSUE THREAD

**Issue by JohnAReid** [syl22-00/pocketsphinx.js#79]
Sorry - it is not really an issue but is is really bugging me and I cannot find the reason why.

I am trying to refactor the web example code to fully understand the logic behind it. 
However after hours of  checking I am hitting a brick wall regarding the words being returned by the recogniser.

```
while (buffer.size() < array.length) buffer.push_back(0);
for (var i = 0 ; i < array.length ; i++) buffer.push_back(array[i]);
var check = recognizer.process(buffer);
if (check != Module.ReturnType.SUCCESS)  { console.log(check); return;} recognizer.getHypseg(segmentation);
$scope.recogvalue = recognizer.getHyp();
```
Lets assume the words "One two" was recorded.
So when the first array is passed to the above code it might return "TWO TWO"
when the next array is processed it returns multiple entries i.e.  "TWO TWO TWO TWO"
and so on for the other arrays in the recorder.
After all the arrays have been processed recognizer.stop(); is called and the final recognizer.getHyp(); called with the result being repeated multiple times.

I have checked that the buffer and array size are constant - so I think it must have something to do with the recognizer setup or the way it is being called.

Any hints or suggestions as to what is causing this effect would be highly appreciated.

OK I think the reason is  as per your readme file: 

> Calls to pocketsphinx.js functions are synchronous, that's also why you probably need to load it in a Web Worker, as explained in later sections.

Problem is that I cannot use a Web worker as I want to provide the system as a stand alone system without a server.  I can get the web workers to work by converting the workers to a blob but Chrome  disables importing of scripts so it fails on the the pocketsphinx.js file.

Will have to look at ways to make the calls to  pocketsphinx.js  within  the js code.

**Comment by JohnAReid** [comment]
Sorry after many hours of trying  - I still cannot make it work outside of a webworker - still getting multiply items returned by the recognizer.getHyp(); call.

Looks like it is just something which cannot be done!

**Comment by syl22-00** [comment]
I am not sure I understand your issues:

* For the keyword detection, it will recognize as many instances of the keyword as are recorded. You can adjust the threshold if you see too many false positives or negatives. And for issues not specific to this JavaScript port of Pocketsphinx, you can get more accurate help from CMU Sphinx forum, IRC and mailing list (http://cmusphinx.org).
* Pocketsphinx does not need to run in a web worker, but that's probably the most practical for a real time application. The test suite does not use a web worker. If you do not want to serve the files from a web server, you can run it on Firefox using `file://` or on chrome if you disable web security (that is all explained in the docs).

**Comment by JohnAReid** [comment]
@syl22-00 After many attempts I finally got my attempt to match the example web version - it was just my bad coding in the end - really appreciate the work you have done in the original version.
