### ISSUE TITLE
Designing grammar entries

### ISSUE THREAD

**Issue by JohnAReid** [syl22-00/pocketsphinx.js#81]
Is there any documentation to explain designing grammar entries? I have searched the cmusphinx site - but it seems to build the grammar differently.

The readme file section 3.3 b is easy to understand  - but when looking at the web example:

```
 var grammarOses = {numStates: 7, start: 0, end: 6, transitions: [{from: 0, to: 1, word: "WINDOWS"}, {from: 0, to: 1, word: "LINUX"}, {from: 0, to: 1, word: "UNIX"}, {from: 1, to: 2, word: "IS"}, {from: 2, to: 2, word: "NOT"}, {from: 2, to: 6, word: "GOOD"}, {from: 2, to: 6, word: "GREAT"}, {from: 1, to: 6, word: "ROCKS"}, {from: 1, to: 6, word: "SUCKS"}, {from: 0, to: 4, word: "MAC"}, {from: 4, to: 5, word: "O"}, {from: 5, to: 3, word: "S"}, {from: 3, to: 1, word: "X"}, {from: 6, to: 0, word: "AND"}]};
     
```

The grammar is more complex and I am really guessing with  the following: {from: 1, to: 6, word: "SUCKS"}, {from: 0, to: 4, word: "MAC"}, {from: 4, to: 5, word: "O"}, {from: 5, to: 3, word: "S"}, {from: 3, to: 1, word: "X"}, {from: 6, to: 0, word: "AND"}.

My guess with the following _{from: 1, to: 6, word: "SUCKS"}_ is that the word "SUCKS" can be found in transitions 1 to 2, 2 to 3, 3, to 4, 4 to 5 and 5 to 6.
As for _{from: 6, to: 0, word: "AND"}_ I have no idea what it means.

In addition I wonder what changing the log-probability value will do.

**Comment by nshmyrev** [comment]
It is https://en.wikipedia.org/wiki/Finite_state_grammar, a graph with nodes and transitions between them. Log probability reduces probability of the certain words compared to other words. You can create such graph from JSGF grammar with sphinx_jsgf2fsg command.

**Comment by syl22-00** [comment]
```
find . -name "*.fsg"
```
There are a bunch of FSG files available in the code, they might help you understand what states, transitions and log probabilities do.
