### ISSUE TITLE
Adding words - is stress possible

### ISSUE THREAD

**Issue by JohnAReid** [syl22-00/pocketsphinx.js#82]
The readme file has a link to [ CMU Pronunciation Dictionary site](http://www.speech.cs.cmu.edu/cgi-bin/cmudict) 
Here the "Look up the pronunciation for a word or phrase in CMUdict" function has the option to show Lexical Stress.

So two questions: 
1  - can pocketsphinx.js accept the stress entry - and 
2 (and more importantly) would using the stress entry be more accurate?

**Comment by nshmyrev** [comment]
> 1 - can pocketsphinx.js accept the stress entry - and

No because acoustic model is trained without stress

> 2 (and more importantly) would using the stress entry be more accurate?

It is possible to train acoustic model with stress, it is only marginally more accurate, so not widely used.

**Comment by JohnAReid** [comment]
@nshmyrev Thanks will avoid using the stress option!
