### ISSUE TITLE
Keyword limitation

### ISSUE THREAD

**Issue by JohnAReid** [syl22-00/pocketsphinx.js#83]
Is there any limitation on the number of keywords which can be entered?  I am getting the following error even although I have entered the word in question: (this would have been the 41st keyword)

`ERROR: "kws_search.c", line 528: Word 'ARM' in phrase 'ARM' is missing in the dictionary`

**Comment by syl22-00** [comment]
Looking at your error message, I'd rather look at my dictionary, it seems like the word is missing.

**Comment by JohnAReid** [comment]
@syl22-00  Thanks - you were right - it was one of the words in the dictionary which caused the problem ( I think it rejected the word-pronunciation)  - however after rejecting one it rejected every other keyword added afterwards. Removed the word in question  and it accepted all the key words.
