### ISSUE TITLE
Poor Accuracy in all Tests

### ISSUE THREAD

**Issue by Thread7** [syl22-00/pocketsphinx.js#84]
I tried the live.html demo in a browser and get very poor accuracy.  I can't believe I don't see this already as an open issue.  Others must be seeing the same thing.  I tried Chrome & Firefox.  Windows, Linux & Android.  Myself (male) and my friend (female) as the speakers. (We are native U.S. English speakers).  I downloaded the project and put it on localhost but also tried it from this https://syl22-00.github.io/pocketsphinx.js/live-demo.html

In all cases I get maybe 50% accuracy at best.  Usually worse.  For instance I read the digits zero to nine in order but this was what it recognized:
Final: ZERO NINE FOUR TWO TWO THREE TWO FOUR ONE TWO ONE EIGHT ONE

Now I also downloaded this Android app based on PocketSphinx [https://play.google.com/store/apps/details?id=nl.happyworx.srdemo.demo](https://play.google.com/store/apps/details?id=nl.happyworx.srdemo.demo) and got very good results. 90%+ accuracy.  So I'm not sure why PocketSphinx.js has the issue.  I'm quite confident a vast majority of other people will experience the same issues if they try the demos.  Is there something I am missing?

**Comment by nshmyrev** [comment]
Default demo includes tiny rm1 model as far as I understand, you need to plug latest pocketsphinx model instead.

**Comment by syl22-00** [comment]
So as @nshmyrev said, the shipped acoustic model is tiny, if one wants to build a serious app, it is probably necessary to use a larger one such as the one available upstream.

Also I am not sure exactly how you test, but the digits language model is quite prone to confusion as any list of digit is equally likely and digits are short words that possibly have many overlaps in their pronunciations. If you tested more constrained language models (the OSes example), or longer words (such as the cities example), you'd get higher accuracy.

Another thing is that CMN is currently based on earlier utterances, so you'll get much lower accuracy at your first spoken utterance than for subsequent ones.

And finally, `pocketsphinx.js` uses exactly `pocketsphinx` code, so with the same acoustic and language models, and audio recording device, you'll get the same thing.

I hope those help.

**Comment by Thread7** [comment]
Thanks so much.  This is good news.  I've been reading the docs on inserting another acoustic model so I can get a more accurate test quickly.  Recompiling with empscripten looks a bit daunting but hopefully I can figure it out!
