### ISSUE TITLE
How to Build with my own Models

### ISSUE THREAD

**Issue by Thread7** [syl22-00/pocketsphinx.js#86]
I've followed the docs for packaging my own model.  It may have worked, but I don't think so.  I thought it would generate a pocketsphinx.js file for me.  But it did not.  What I get inside my build directory is a CMakeFiles directory, a hub4-8gau directory, and an include directory.  The only thing in include is `pocketsphinxjs-config.h.`  The hub4-8gau directory has the following files:
`8gau.6000sen.quant
feat.params
mdef
means
mixture_weights
mllr_matrices
noisedict
README
transition_matrices
variances`

I ran this statement to start the build process
`cmake -DEMSCRIPTEN=1 -DCMAKE_TOOLCHAIN_FILE=c:/software/emcc/emscripten/1.35.0/cmake/Modules/Platform/Emscripten.cmake -DHMM_BASE=am -DHMM_FOLDERS=hub4-8gau ..`

(BTW, I am on Windows)

Then at the command prompt I get a bunch of CMake Deprecation Warnings.
But in the end it tells me this:
**-- Building for: NMake Makefiles
-- Configuring done
-- Generating done
-- Build files have been written to: C:/inetpub/pockets/build**

So I don't get any terrible errors.  Am I supposed to get a pocketsphinx.js output?  If not, how do I use those generated files to replace the default configuration?  I want to try the webapp/live.html with this new acoustic model.

**Comment by nshmyrev** [comment]
> Am I supposed to get a pocketsphinx.js output? 

Yes

**Comment by syl22-00** [comment]
this is more an emscripten question.
