### ISSUE TITLE
Switching between grammars and the list of key phrases loaded with lazyload

### ISSUE THREAD

**Issue by karamanos** [syl22-00/pocketsphinx.js#94]
I am trying to write a command and control application using pocketsphinx.js inside a web worker with recognizer.js. 
I have loaded a list of key phrases and the respective dictionary entries using "lazyload".
I also loaded two grammars using the "addGrammar" command (let's assume assigned ids = id1, id2).
Given that the only way to switch between keyword spotting and grammars is via the "start" command (taking as parameter the desired id) how can I alternate between keyword spotting and grammars (i.e. what id should I use for keyword spotting, given that the keywords were loaded with "lazyload")?
My understanding of the desired flow is:
start(keyword spotting id) -> recognized command -> start(id of respective grammar)   
and then again 
start(keyword spotting id) -> recognized command -> start(id of respective grammar)   
Any assistance will be greatly appreciated.

**Comment by syl22-00** [comment]
@karamanos that's a good question. I do not know the answer, but it should not be too difficult to find out, maybe they start with 0?
Another way you could do is to use two recognizers: one for keyword spotting, the other one with grammars?
If you find out, it would be great to give the answer here, or better, in the README.

**Comment by karamanos** [comment]
Many thanks for the answer. I experimented some more with it. The "lazyload" command does not return any id for the loaded list of key phrases. Interestingly also the subsequent first "addGrammar" command returns an id of 0 (not 1). It appears that there is no way to go back to keyword spotting?
I also had a look at item: http://stackoverflow.com/questions/39069614/pocketsphinx-how-to-switch-from-keyword-spotting-to-grammar-mode
Could it be that a  new command needs to be added to recognizer.js in order to achieve the desired switching back to the list of key phrases?

**Comment by karamanos** [comment]
As a workaround, I was able to switch back to keyword spotting by re-initialising the recognizer each time and starting keyword recognition without specifying an id on the start command. Not the best solution but seems to work...

**Comment by karamanos** [comment]
@syl22-00  
It works like a charm! 
Many thanks for the update.

**Comment by nshmyrev** [comment]
Hey @syl22-00, thank you looks great. I just wanted to note that it would be great to have string search names like everywhere else instead of numeric identifiers. Let me know what do you think.
