### ISSUE TITLE
Lazy load model

### ISSUE THREAD

**Issue by JohnAReid** [syl22-00/pocketsphinx.js#96]
This is the procedure I am using for loading the French model cmusphinx-fr-ptm-5.2.tar.gz
1 - start  recognizer
2 - load model as 

```
{command: 'lazyLoad',
          data: {
               folders: [["/", "cmusphinx-fr-5.2"]],
               files: [
                    ["cmusphinx-fr-5.2", "means",  "../cmusphinx-fr-5.2/means"],
                    ["cmusphinx-fr-5.2", "variances",  "../cmusphinx-fr-5.2/variances"],
                    ["cmusphinx-fr-5.2", "transition_matrices",  "../cmusphinx-fr-5.2/transition_matrices"],
                    ["cmusphinx-fr-5.2", "noisedict",  "../cmusphinx-fr-5.2/noisedict"],
                    ["cmusphinx-fr-5.2", "mdef",  "../cmusphinx-fr-5.2/mdef"],
                    ["cmusphinx-fr-5.2", "feat.params",  "../cmusphinx-fr-5.2/feat.params"],
                    ["cmusphinx-fr-5.2", "mixture_weights",  "../cmusphinx-fr-5.2/mixture_weights"],
                    ["cmusphinx-fr-5.2", "feature_transform",  "../cmusphinx-fr-5.2/feature_transform"],
                    ["cmusphinx-fr-5.2", "sendump", "../cmusphinx-fr-5.2/sendump"]
               ]
          }});
```
3 - initRecognizer with  data: [["-hmm", "cmusphinx-fr-ptm-5.2"], ["-fwdflat", "no"]]

the initialize is reporting the following

pocketsphinx.js:1 INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from cmusphinx-fr-5.2/feat.params:

plus an extra 120 console notes then the the last line say:
ERROR: "feat.c", line 311: Total dimensionality of subvector specification 39 > feature dimensionality 32

Not sure how to correct this error within pocketsphinx.

**Comment by nshmyrev** [comment]
You confuse cmusphinx-fr-5.2 and cmusphinx-fr-ptm-5.2, you need to use ptm version. Ptm version does not have feature_transform, you need to remove that file and the corresponding line in lazyload.

**Comment by JohnAReid** [comment]
Thanks @nshmyrev that kind of worked.

 I used the **cmusphinx-fr-5.2.tar.gz** download which did contain the file **feature_transform** but it did not have  **sendump** - so I assumed it was sendump which should be excluded.


Just is case it might help other people....


```
({command: 'lazyLoad',
          data: {
               folders: [["/", "cmusphinx-fr-5.2"]],
               files: [
                    ["cmusphinx-fr-5.2", "means",  "../cmusphinx-fr-5.2/means"],
                    ["cmusphinx-fr-5.2", "variances",  "../cmusphinx-fr-5.2/variances"],
                    ["cmusphinx-fr-5.2", "transition_matrices",  "../cmusphinx-fr-5.2/transition_matrices"],
                    ["cmusphinx-fr-5.2", "noisedict",  "../cmusphinx-fr-5.2/noisedict"],
                    ["cmusphinx-fr-5.2", "mdef",  "../cmusphinx-fr-5.2/mdef"],
                    ["cmusphinx-fr-5.2", "feat.params",  "../cmusphinx-fr-5.2/feat.params"],
                    ["cmusphinx-fr-5.2", "mixture_weights",  "../cmusphinx-fr-5.2/mixture_weights"],
                    ["cmusphinx-fr-5.2", "feature_transform",  "../cmusphinx-fr-5.2/feature_transform"]
               ]
          }}
```

**Comment by JohnAReid** [comment]
OK I have now used **cmusphinx-fr-ptm**-5.2 which does have a sendump file.

The choice of files is rather confusing!
